services:
  devcontainer:
    container_name: devcontainer-rails-mermaid-erd
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - bundle_data:/usr/local/bundle
    command: /bin/sh
    tty: true
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      RAILS_ENV: test

  db:
    container_name: rails-mermaid-erd-db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  bundle_data:
  postgresql_data:
