require "spec_helper"

describe RailsMermaidErd::MermaidText do
  describe ".build" do
    it "renders the header, tables with columns, and relations as erDiagram source" do
      result = {
        Models: [
          {
            TableName: "users",
            TableComment: "app users",
            ModelName: "User",
            IsModelExist: true,
            Columns: [
              {name: "id", type: :integer, key: "PK", comment: nil},
              {name: "team_id", type: :integer, key: "FK", comment: "owning team"}
            ]
          }
        ],
        Relations: [
          {LeftModelName: "Team", LeftValue: "||", Line: "--", RightModelName: "User", RightValue: "o{", Comment: "HM:users"}
        ]
      }

      expect(described_class.build(result)).to eq(<<~MERMAID.chomp)
        erDiagram
            %% --------------------------------------------------------
            %% Generated by "Rails Mermaid ERD"
            %% https://github.com/koedame/rails-mermaid_erd
            %% --------------------------------------------------------

            %% table name: users
            %% table comment: app users
            User {
                integer id PK ""
                integer team_id FK "owning team"
            }

            Team ||--o{ User : "HM:users"
      MERMAID
    end

    it "renders an empty comment when a column has no comment" do
      result = {
        Models: [{
          TableName: "posts", TableComment: "", ModelName: "Post", IsModelExist: true,
          Columns: [{name: "title", type: :string, key: "", comment: nil}]
        }],
        Relations: []
      }

      expect(described_class.build(result)).to include(%(        string title  ""))
    end

    it "sanitises comments so quotes and newlines can't break the diagram" do
      result = {
        Models: [{
          TableName: "widgets",
          TableComment: "multi\nline\ncomment",
          ModelName: "Widget",
          IsModelExist: true,
          Columns: [{name: "size", type: :string, key: "", comment: %(width in "px"\nor mm)}]
        }],
        Relations: []
      }

      output = described_class.build(result)

      # Newlines collapse to a space in the `%% table comment:` line so the
      # remainder can't leak out as diagram source.
      expect(output).to include("    %% table comment: multi line comment")
      # In the quoted column label: `"` -> `#quot;` and newline -> space.
      expect(output).to include(%(        string size  "width in #quot;px#quot; or mm"))
    end

    it "replaces every ':' in namespaced model names with '-' so Mermaid can parse them (matching the viewer)" do
      result = {
        Models: [{TableName: "admin_users", TableComment: "", ModelName: "Admin::User", IsModelExist: true, Columns: []}],
        Relations: [{LeftModelName: "Admin::Team", LeftValue: "||", Line: "--", RightModelName: "Admin::User", RightValue: "o{", Comment: "HM:users"}]
      }

      output = described_class.build(result)
      expect(output).to include("    Admin--User {")
      expect(output).to include("    Admin--Team ||--o{ Admin--User : ")
    end
  end
end
